import { MailService } from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  throw new Error("SENDGRID_API_KEY environment variable must be set");
}

const mailService = new MailService();
mailService.setApiKey(process.env.SENDGRID_API_KEY);

interface SupportTicketEmailParams {
  ticketNumber: string;
  subject: string;
  message: string;
  userEmail: string;
  userName: string;
  category: string;
  priority: string;
  attachments?: string[];
}

export async function sendSupportTicketEmail(params: SupportTicketEmailParams): Promise<boolean> {
  try {
    const emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #e11d48; border-bottom: 2px solid #e11d48; padding-bottom: 10px;">
          🎫 New Support Ticket - ${params.ticketNumber}
        </h2>
        
        <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #333;">Ticket Details</h3>
          <p><strong>Subject:</strong> ${params.subject}</p>
          <p><strong>Category:</strong> ${params.category}</p>
          <p><strong>Priority:</strong> ${params.priority}</p>
          <p><strong>User:</strong> ${params.userName} (${params.userEmail})</p>
        </div>
        
        <div style="background-color: #fff; padding: 20px; border-left: 4px solid #e11d48; margin: 20px 0;">
          <h4 style="margin-top: 0; color: #333;">Message:</h4>
          <p style="white-space: pre-wrap; line-height: 1.6;">${params.message}</p>
        </div>
        
        ${params.attachments && params.attachments.length > 0 ? `
          <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h4 style="margin-top: 0; color: #333;">📎 Attachments:</h4>
            <ul>
              ${params.attachments.map(url => `<li><a href="${url}" target="_blank">${url}</a></li>`).join('')}
            </ul>
          </div>
        ` : ''}
        
        <div style="background-color: #f3f4f6; padding: 15px; border-radius: 8px; margin: 20px 0; text-align: center;">
          <p style="margin: 0; color: #666; font-size: 14px;">
            This ticket has been automatically forwarded to the VeriFund admin panel for review and assignment.
          </p>
        </div>
        
        <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 20px; text-align: center;">
          <p style="color: #666; font-size: 12px; margin: 0;">
            Generated by VeriFund Support System | ${new Date().toLocaleString()}
          </p>
        </div>
      </div>
    `;

    await mailService.send({
      to: 'trexiaamble@gmail.com',
      from: 'noreply@verifund.com', // You may need to verify this domain in SendGrid
      subject: `[VeriFund Support] ${params.ticketNumber}: ${params.subject}`,
      html: emailContent,
      text: `
        New Support Ticket: ${params.ticketNumber}
        
        Subject: ${params.subject}
        Category: ${params.category}
        Priority: ${params.priority}
        User: ${params.userName} (${params.userEmail})
        
        Message:
        ${params.message}
        
        ${params.attachments && params.attachments.length > 0 ? `
        Attachments:
        ${params.attachments.map(url => `- ${url}`).join('\n')}
        ` : ''}
        
        View and manage this ticket in the VeriFund admin panel.
      `,
    });
    
    return true;
  } catch (error) {
    console.error('SendGrid email error:', error);
    return false;
  }
}

// Admin notification email for ticket updates
export async function sendTicketStatusUpdateEmail(params: {
  ticketNumber: string;
  subject: string;
  status: string;
  adminName: string;
  adminEmail: string;
  resolutionNotes?: string;
}): Promise<boolean> {
  try {
    const emailContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #059669; border-bottom: 2px solid #059669; padding-bottom: 10px;">
          ✅ Ticket Status Update - ${params.ticketNumber}
        </h2>
        
        <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3 style="margin-top: 0; color: #333;">Update Details</h3>
          <p><strong>Ticket:</strong> ${params.ticketNumber}</p>
          <p><strong>Subject:</strong> ${params.subject}</p>
          <p><strong>New Status:</strong> <span style="background-color: #059669; color: white; padding: 4px 8px; border-radius: 4px;">${params.status}</span></p>
          <p><strong>Handled by:</strong> ${params.adminName} (${params.adminEmail})</p>
        </div>
        
        ${params.resolutionNotes ? `
          <div style="background-color: #f0fdf4; padding: 20px; border-left: 4px solid #059669; margin: 20px 0;">
            <h4 style="margin-top: 0; color: #333;">Resolution Notes:</h4>
            <p style="white-space: pre-wrap; line-height: 1.6;">${params.resolutionNotes}</p>
          </div>
        ` : ''}
        
        <div style="border-top: 1px solid #e5e7eb; padding-top: 20px; margin-top: 20px; text-align: center;">
          <p style="color: #666; font-size: 12px; margin: 0;">
            VeriFund Support System | ${new Date().toLocaleString()}
          </p>
        </div>
      </div>
    `;

    await mailService.send({
      to: 'trexiaamble@gmail.com',
      from: 'noreply@verifund.com',
      subject: `[VeriFund Support] ${params.ticketNumber} Status: ${params.status}`,
      html: emailContent,
    });
    
    return true;
  } catch (error) {
    console.error('SendGrid email error:', error);
    return false;
  }
}